language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: r8/Im0UcstaTgjyI5EUf/2SatNzeCS6RXgVlELUT1mqjbM5kbCOwqW27iW/1cdGMCDQx05u8X/scH3x/6UWJrf5e1NYeiZCOnPXo2ZGgd5u9qDCnwaPnJNgcRg1Iislmcnw9pLoXE/E8P55mPaCbj6m9H6vVmlzJVg0GEDZzT3lonHAk0WlgpnYpsgMvUkqfkU6W+p223cnKJLEsrizJ/kP6E+Rn6W0BJumiWmbFF8qJGT3kxbCCe++JrFh1ZabtBV/D04eVrOS0QGBtv6Ke17eYscGvPsub7yddntzZPoSsfreUoUlZBKinWgepCx4Ef6XqDlf2XjbLkAJoIYnSrBch4NI5pgzWX+S/BrMh0OSWCk0aODwAYD60gG5bu0pPAWjqFD/Vj/Hw7+x8/6ZLIGO+VO5Yr65Yoe8xGhA4RIW+ZFOqqCGGxJf3jonI6olcq/R/+KTGyOTZAJzHKrkPecA9277cqVOp1+/BrOBbAaSJlDk+8qRFyCAnosYSncBuxqaNjaeQF6A8JY3Nm55GDw31ht9LSJ9Q4x0nO1+jwJC8bs4WvQ17vuPoIb3LlYBBAFBunWZQsgEXTedzaW0FE1n+nzAg0HHWdAjiuAMiDtiGOTu5DVcEcpCt2Q/Z0yQCq0rKqTfWkxpHE+dUTEg1KAbp4gMLSDdy4xzZwH4k1Ow=
    # FIREBASE_SECRET
    - secure: c+9yF9BQkw4vRsjGuOpQ2Ty9OP+tx8aCUUN4oTtfq1yZ0UGKzZIjdSHKGI8ze+mmuTVHGdjo0sIMHJ+uLabXlmDYGaDIZCKsIRHAAg1PvBvWmZfz0iqstC2JPJxHrt8XrubLbqs1owjv5gzHSWBlGfm1OyiM/ykqWiuzAhn7FgajdZ0PaB90lqIbNWvDvTN3oH05/TzxKD6e74YSqEOD4ZWClF7una79Wbyfamw5pYLWChiRPeURfwwvmJkFTJb9IGqqeEjPwl/h05G6aeDUkJq+uVFBi+OjxSqHTvdglbo/QQFwTg9nulmi80uuwUUwf7oxaRXhhySGAhUlMa3A9cc2b+pwYF4CTrMZHmu0sekTQ3RmYf4+vKIQ0fP0B9SQsCRVwN0ycnr8Q6cgLyVy7NAEAzsljwMOaTIfFJTfEsncE2ebJWHwiYkjEUtT7PXXKo+oYqBpoefasbhTgbn/Zq7ZJS2mswEpEezeyyJinL8awY+k68P3Ebl2LZ7wjILUddh8/iY0bPomG2xU4se+o0HKky8cxS+VN7vX5bzjRmwQjN1t0kHldI53GtwJv8ZSy3JspnZpv5sC+UrT3n9jBd9RFXRyrJ3DPBSpaZ1Zg8FFYIX+ePQrAc0F2EWwwG7UzH0gxu28XAPrZvQ7s9A9vYN5pg8emVyviSAMdCJgxRk=
